Fix build script, fix shulker boxes, add shields
OroArmorModding/Netherite-Plus-Mod pull request #156
Opened 2024-06-25 20:05 UTC by Roadhog360

Now correct sound, rotation fixed

2024-06-25 23:09 UTC, Roadhog360 commented
Might revert Quilt to 0.26.0, beta version seems unnecessary

2024-06-26 06:50 UTC, Roadhog360 commented
Feel free to ask me to remove the self-attribution upon request, these changes are ultimately small so I'd understand.

## NOTE: Once you pull these changes you will need to add Multi-Item-Lib and update the version in the scripts and `quilt.mod.json` yourself to require the new version

I can't push stuff to your maven so I left it alone as to not make the script unable to build, so you can test the other changes. But the Multi-Item-Lib update is required for shield disabling to work on top of the multitude of mixin fixes for compatibility.

2024-06-26 08:25 UTC, Roadhog360 commented
I'm also going to add ELYTRA back to Multi-Item-Lib as the Netherite Elytra registered as an elytra is causing a few issues, like cape still rendering and other checks for elytra failing. I'll fix this in MIL. I can make another PR for this and the MIL version bump if you push MIL to your maven

2024-06-27 21:09 UTC, Roadhog360 commented
So I decided to temporarily place MIL in libs and load it as a jar dependency so you don't need to do any manual work to test the new changes. So all you need to do if you accept the changes, is to simply change the buildscript to use the maven again and delete the jar. I can do this from my end if you want, just pull 1.6.3 MIL into your Maven and lmk to fix the dep setup

2024-07-06 05:12 UTC, OroArmor requested changes

2024-07-06 05:12 UTC, OroArmor commented on build.gradle
>      id 'com.oroarmor.minecraft-gradle-plugin' version '1.2.3'
```suggestion
    id 'com.oroarmor.general-gradle-plugin' version '1.3.1'
    id 'com.oroarmor.minecraft-gradle-plugin' version '1.3.1'

```

2024-07-06 05:12 UTC, OroArmor commented on build.gradle
> +            version = "1.6.3"
```suggestion
            version = "1.7.0"

```

2024-07-06 05:12 UTC, OroArmor commented on src/main/java/com/oroarmor/netherite_plus/client/NetheritePlusClientMod.java
> -        }));
Ah thanks for getting rid of this, it was pretty hacky

2024-07-06 05:12 UTC, OroArmor commented on src/main/java/com/oroarmor/netherite_plus/item/NetheriteElytraArmorMaterials.java
>  public enum NetheriteElytraArmorMaterials implements ArmorMaterial {
I think we should try to remove this.

2024-07-06 05:12 UTC, OroArmor commented on src/main/java/com/oroarmor/netherite_plus/item/NetheriteElytraItem.java
> +public class NetheriteElytraItem extends ElytraItem implements FabricElytraItem {
Does repairing this with netherite still work or is it back to phantom membrane?

2024-07-06 05:12 UTC, OroArmor commented on build.gradle
> +    modCompileOnly("com.github.CrimsonDawn45:Fabric-Shield-Lib:1.7.2-1.20.2")
Is this still being used?

2024-07-06 10:03 UTC, Roadhog360 commented
I didn't notice you reviewed. I'll read soon, give me a day or two.

2024-07-06 19:07 UTC, OroArmor commented
I finished the review 5 days ago put forgot to actually send it.

2025-12-26 18:29 UTC, Roadhog360 commented
I quit modern modding for now and went back to 1.7.10

2025-12-26 18:29 UTC, closed without merging